import BookmarkPrimitive
import CommentPrimitive
import Foundation
import RichTextPrimitive
import SearchPrimitive
import TrackChangesPrimitive

public enum DocumentSearchScope: String, CaseIterable, Sendable {
    case headings
    case comments
    case bookmarks
    case changes

    var label: String {
        switch self {
        case .headings:
            "Headings"
        case .comments:
            "Comments"
        case .bookmarks:
            "Bookmarks"
        case .changes:
            "Changes"
        }
    }

    var systemImage: String {
        switch self {
        case .headings:
            "list.bullet.indent"
        case .comments:
            "text.bubble"
        case .bookmarks:
            "bookmark"
        case .changes:
            "arrow.triangle.branch"
        }
    }
}

struct DocumentSearchNavigatorItem: Identifiable, Equatable, Sendable {
    let sourceID: String
    let scope: DocumentSearchScope
    let title: String
    let subtitle: String
    let pageNumber: Int?
    let contentID: String?
    let offset: Int
    let snippet: String?
    let score: Double?

    var id: String {
        "\(scope.rawValue):\(sourceID)"
    }

    var statusLabel: String {
        switch scope {
        case .headings:
            "Heading"
        case .comments:
            "Comment"
        case .bookmarks:
            "Bookmark"
        case .changes:
            "Change"
        }
    }

    var systemImage: String {
        scope.systemImage
    }
}

struct DocumentSearchEntry: Identifiable, Equatable, Sendable, Indexable {
    let id: String
    let scope: DocumentSearchScope
    let title: String
    let body: String
    let subtitle: String
    let contentID: String?
    let pageNumber: Int?
    let offset: Int

    func indexableFields() -> [IndexableField] {
        [
            IndexableField(
                name: "title",
                value: title,
                options: FieldOptions(searchable: true, facetable: false, boost: 3.0)
            ),
            IndexableField(
                name: "body",
                value: body,
                options: FieldOptions(searchable: true, facetable: false, boost: 1.5)
            ),
            IndexableField(
                name: "subtitle",
                value: subtitle,
                options: FieldOptions(searchable: true, facetable: false, boost: 1.0)
            ),
            IndexableField(
                name: "scope",
                value: scope.rawValue,
                options: FieldOptions(searchable: false, facetable: true, boost: 1.0)
            ),
        ]
    }
}

struct DocumentSearchNavigatorResults: Sendable {
    let items: [DocumentSearchNavigatorItem]
    let totalCount: Int
    let facetCounts: [DocumentSearchScope: Int]
}

@MainActor
extension DocumentEditorState {
    var documentSearchEntries: [DocumentSearchEntry] {
        let summaryResolver = TrackedChangeSummaryResolver()

        let headingEntries = document.sections.flatMap { section in
            section.blocks.compactMap { block -> DocumentSearchEntry? in
                guard case let .heading(content, level) = block.content else { return nil }
                let title = documentSearchTrimmedPreview(content.plainText, fallback: "Untitled heading")
                return DocumentSearchEntry(
                    id: "heading:\(block.id.rawValue)",
                    scope: .headings,
                    title: title,
                    body: content.plainText,
                    subtitle: "Heading \(level)",
                    contentID: block.id.rawValue,
                    pageNumber: layoutEngine.pageNumber(for: block.id),
                    offset: 0
                )
            }
        }

        let commentEntries = commentStore.comments.map { comment in
            let preview = documentSearchTrimmedPreview(comment.body, fallback: "Untitled comment")
            return DocumentSearchEntry(
                id: "comment:\(comment.id.rawValue)",
                scope: .comments,
                title: preview,
                body: comment.body,
                subtitle: "\(documentSearchCommentStatusLabel(comment.status)) by \(comment.author.rawValue)",
                contentID: anchoredContentID(for: comment),
                pageNumber: documentSearchPageNumber(for: anchoredContentID(for: comment)),
                offset: documentSearchCommentOffset(comment)
            )
        }

        let bookmarkEntries = bookmarkStore.bookmarks.map { bookmark in
            let bookmarkType = bookmark.isAutoGenerated ? "Automatic bookmark" : "Manual bookmark"
            return DocumentSearchEntry(
                id: "bookmark:\(bookmark.id.rawValue)",
                scope: .bookmarks,
                title: bookmark.name,
                body: [bookmark.name, bookmark.metadata.values.joined(separator: " ")]
                    .filter { !$0.isEmpty }
                    .joined(separator: "\n"),
                subtitle: bookmarkType,
                contentID: bookmark.anchor.contentID,
                pageNumber: documentSearchPageNumber(for: bookmark.anchor.contentID)
                    ?? bookmark.metadata["page"].flatMap(Int.init),
                offset: bookmark.anchor.offset ?? 0
            )
        }

        let changeEntries = reviewableTrackedChanges.map { change in
            let summary = summaryResolver.summary(for: change, context: trackedChangeContexts[change.id])
            let body = documentSearchChangeBody(change)
            let changeType = documentSearchChangeTypeLabel(change.type)

            return DocumentSearchEntry(
                id: "change:\(change.id.rawValue)",
                scope: .changes,
                title: summary,
                body: [summary, body].filter { !$0.isEmpty }.joined(separator: "\n"),
                subtitle: "\(changeType) by \(change.author.rawValue)",
                contentID: change.anchor.blockID,
                pageNumber: documentSearchPageNumber(for: change.anchor.blockID),
                offset: change.anchor.offset
            )
        }

        return (headingEntries + commentEntries + bookmarkEntries + changeEntries)
            .sorted(by: documentSearchEntrySort)
    }

    func documentSearchResults(
        matching queryText: String,
        scope: DocumentSearchScope? = nil,
        limit: Int = 40
    ) async -> DocumentSearchNavigatorResults {
        let entries = documentSearchEntries
        let filteredEntries = scope.map { target in
            entries.filter { $0.scope == target }
        } ?? entries

        guard let query = makeDocumentSearchQuery(from: queryText), !entries.isEmpty else {
            let facetCounts = documentSearchFacetCounts(for: entries)
            let items = filteredEntries.prefix(limit).map {
                documentSearchNavigatorItem(from: $0, score: nil, snippet: nil)
            }
            return DocumentSearchNavigatorResults(
                items: items,
                totalCount: filteredEntries.count,
                facetCounts: facetCounts
            )
        }

        let index = SearchIndex<DocumentSearchEntry>()
        await index.index(entries)

        do {
            let searchResults = try await index.search(query, facets: ["scope"], limit: entries.count)
            let scopedResults = scope.map { target in
                searchResults.results.filter { $0.document.scope == target }
            } ?? searchResults.results
            let items = scopedResults.prefix(limit).map { result in
                documentSearchNavigatorItem(
                    from: result.document,
                    score: result.score,
                    snippet: documentSearchSnippet(from: result)
                )
            }
            return DocumentSearchNavigatorResults(
                items: items,
                totalCount: scopedResults.count,
                facetCounts: documentSearchFacetCounts(from: searchResults.facets["scope"] ?? [])
            )
        } catch {
            return DocumentSearchNavigatorResults(
                items: filteredEntries.prefix(limit).map { documentSearchNavigatorItem(from: $0, score: nil, snippet: nil) },
                totalCount: filteredEntries.count,
                facetCounts: documentSearchFacetCounts(for: entries)
            )
        }
    }

    func focusDocumentSearchResult(_ item: DocumentSearchNavigatorItem) {
        switch item.scope {
        case .headings:
            guard let contentID = item.contentID else { return }
            focusDocumentSelection(.caret(BlockID(contentID), offset: item.offset))
        case .comments:
            focusComment(CommentID(rawValue: item.sourceID))
        case .bookmarks:
            focusBookmark(BookmarkID(rawValue: item.sourceID))
        case .changes:
            focusChange(ChangeID(rawValue: item.sourceID))
        }
    }

    func isFocusedDocumentSearchResult(_ item: DocumentSearchNavigatorItem) -> Bool {
        switch item.scope {
        case .headings:
            return richTextState.focusedBlockID?.rawValue == item.contentID
        case .comments:
            return currentComment?.id.rawValue == item.sourceID
        case .bookmarks:
            return richTextState.focusedBlockID?.rawValue == item.contentID
        case .changes:
            return currentTrackedChangeID?.rawValue == item.sourceID
        }
    }

    private func documentSearchNavigatorItem(
        from entry: DocumentSearchEntry,
        score: Double?,
        snippet: String?
    ) -> DocumentSearchNavigatorItem {
        let sourceID = entry.id.split(separator: ":", maxSplits: 1).dropFirst().first.map(String.init) ?? entry.id
        return DocumentSearchNavigatorItem(
            sourceID: sourceID,
            scope: entry.scope,
            title: entry.title,
            subtitle: entry.subtitle,
            pageNumber: entry.pageNumber,
            contentID: entry.contentID,
            offset: entry.offset,
            snippet: snippet,
            score: score
        )
    }

    private func makeDocumentSearchQuery(from text: String) -> SearchQuery? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        if trimmed.hasPrefix("\""), trimmed.hasSuffix("\""), trimmed.count > 1 {
            return .phrase(String(trimmed.dropFirst().dropLast()))
        }

        let parts = trimmed
            .split(whereSeparator: \.isWhitespace)
            .map(String.init)

        guard !parts.isEmpty else { return nil }
        if parts.count == 1 {
            return .term(parts[0])
        }

        return .and(parts.map(SearchQuery.term))
    }

    private func documentSearchSnippet(
        from result: SearchResult<DocumentSearchEntry>
    ) -> String? {
        result.highlights["body"]?.first?.snippet
            ?? result.highlights["title"]?.first?.snippet
            ?? result.highlights["subtitle"]?.first?.snippet
    }

    private func documentSearchFacetCounts(
        from facets: [Facet]
    ) -> [DocumentSearchScope: Int] {
        facets.reduce(into: [DocumentSearchScope: Int]()) { partialResult, facet in
            guard let scope = DocumentSearchScope(rawValue: facet.value) else { return }
            partialResult[scope] = facet.count
        }
    }

    private func documentSearchFacetCounts(
        for entries: [DocumentSearchEntry]
    ) -> [DocumentSearchScope: Int] {
        entries.reduce(into: [DocumentSearchScope: Int]()) { partialResult, entry in
            partialResult[entry.scope, default: 0] += 1
        }
    }

    private func documentSearchEntrySort(_ lhs: DocumentSearchEntry, _ rhs: DocumentSearchEntry) -> Bool {
        let lhsOrder = documentSearchOrder(for: lhs)
        let rhsOrder = documentSearchOrder(for: rhs)

        if lhsOrder != rhsOrder {
            return lhsOrder < rhsOrder
        }

        if lhs.offset != rhs.offset {
            return lhs.offset < rhs.offset
        }

        if lhs.scope.rawValue != rhs.scope.rawValue {
            return lhs.scope.rawValue < rhs.scope.rawValue
        }

        return lhs.id < rhs.id
    }

    private func documentSearchOrder(for entry: DocumentSearchEntry) -> Int {
        guard let contentID = entry.contentID else { return .max }
        return document.sections
            .flatMap(\.blocks)
            .firstIndex(where: { $0.id.rawValue == contentID }) ?? .max
    }

    private func documentSearchPageNumber(for contentID: String?) -> Int? {
        guard let contentID else { return nil }
        return layoutEngine.pageNumber(for: BlockID(contentID))
    }

    private func documentSearchCommentOffset(_ comment: Comment) -> Int {
        switch comment.anchor.anchorType {
        case TextCommentAnchor.anchorType:
            return (try? comment.anchor.resolve(TextCommentAnchor.self).offset) ?? 0
        case ObjectCommentAnchor.anchorType:
            return 0
        default:
            return 0
        }
    }

    private func documentSearchCommentStatusLabel(_ status: CommentStatus) -> String {
        switch status {
        case .open:
            "Open comment"
        case .resolved:
            "Resolved comment"
        case .wontFix:
            "Won't-fix comment"
        }
    }

    private func documentSearchChangeTypeLabel(_ type: ChangeType) -> String {
        switch type {
        case .insertion:
            "Insertion"
        case .deletion:
            "Deletion"
        case .formatChange:
            "Formatting change"
        }
    }

    private func documentSearchChangeBody(_ change: TrackedChange) -> String {
        switch change.type {
        case let .insertion(text), let .deletion(text):
            text
        case let .formatChange(from, to):
            [from, to]
                .map { value in
                    value
                        .map { "\($0.key): \($0.value)" }
                        .sorted()
                        .joined(separator: ", ")
                }
                .joined(separator: "\n")
        }
    }

    private func documentSearchTrimmedPreview(_ text: String, fallback: String) -> String {
        let trimmed = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "\n", with: " ")
        guard !trimmed.isEmpty else { return fallback }
        return String(trimmed.prefix(72))
    }
}
